atasnap:
  prefix_exec: /home/sonata/src/hashpipe/src/
  prefix_lib: /home/sonata/dev/dm_hpguppi_daq/src/.libs/
  # hpguppi_plugin:
  logdir: /home/sonata/logs
  # command_prefix:
  setup_commands:
    - /opt/mnt/bin/kill_redis_gateway.sh $INSTANCE
    - pkill -ef hashpipe_status_monitor
    - ipcrm -a
  # post_commands:
  #   - sleep 5
  #   - /opt/mnt/bin/init_redis_gateway.sh $INSTANCE
  hashpipe_keyfile: /home/sonata
  environment:
    - ATASHAREDIR="/opt/mnt"
    - GEM_PATH=/home/sonata/.rvm/gems/ruby-2.1.10/bin
    # - LD_LIBRARY_PATH=/opt/mnt/lib:$LD_LIBRARY_PATH
    - LD_LIBRARY_PATH=/home/sonata/dev/dm_hpguppi_daq/src:/home/sonata/src/hashpipe/src:/opt/mnt/lib
    - PATH=/opt/mnt/bin:$PATH:/home/sonata/.rvm/rubies/ruby-2.1.10/bin:/home/sonata/.rvm/bin
    # sudo HASHPIPE_KEYFILE=/home/sonata PATH=/home/sonata/.rvm/rubies/ruby-2.1.10/bin:/home/sonata/.rvm/bin:$PATH GEM_PATH=/home/sonata/.rvm/gems/ruby-2.1.10/bin /opt/mnt/bin/init_redis_gateway.sh 0
  options:
    - IBVPKTSZ=42,16,8208
    - BINDPORT=10000
  instance_numanode_bind: [1, 0]
  instance_datadir: [/mnt/buf0, /mnt/buf1]
  instance_bindhost: [enp97s0f1, enp225s0f1]
  thread_mask_lengths:
    hpguppi_atasnap_pkt_to_FTP_transpose:
      8
  subsystem_threads:
    ibv:
      - hpguppi_ibvpkt_thread
      - hpguppi_atasnap_ibv_voltage_thread
      - hpguppi_atasnap_pkt_to_FTP_transpose
      - hpguppi_atasnap_rawdisk_thread
    ibv_optimised:
      - hpguppi_ibvpkt_thread
      - hpguppi_atasnap_ibv_voltage_only_thread
      - hpguppi_atasnap_control_thread
      - hpguppi_atasnap_pkt_to_FTP_transpose
      - hpguppi_atasnap_rawdisk_thread
    pktsock:
      - hpguppi_atasnap_pktsock_thread
      - hpguppi_atasnap_pkt_to_FTP_transpose
      - hpguppi_atasnap_rawdisk_thread
    pktsock_optimised:
      - hpguppi_atasnap_pktsock_only_thread
      - hpguppi_atasnap_control_thread
      - hpguppi_atasnap_pkt_to_FTP_transpose
      - hpguppi_atasnap_rawdisk_thread
  cpu_core_count_config: #[16]
    16:
      instance_cpu_core_0: [0, 16]
      instance_subsystem_thread_masks:
        ibv:
          hpguppi_ibvpkt_thread: [10,26]
          hpguppi_atasnap_ibv_voltage_thread: [0, 16]
