atasnap_ibv:
  prefix_exec: /home/sonata/src/hashpipe/src/
  prefix_lib: /home/sonata/dev/dm_hpguppi_daq/src/.libs/
  # hpguppi_plugin:
  logdir: /home/sonata/logs
  # command_prefix:
  hashpipe_keyfile: /home/sonata
  environment:
    - LD_LIBRARY_PATH=/home/sonata/dev/dm_hpguppi_daq/src:/home/sonata/src/hashpipe/src:/opt/mnt/lib
    - PATH=$PATH:/opt/mnt/:/opt/mnt/lib
  options:
    - IBVPKTSZ=42,16,8192
    - BINDPORT=10000
  instance_numanode_bind:
    - 1
    - 0
  instance_datadir:
    - /mnt/buf0
    - /mnt/buf1
  instance_bindhost:
    - enp97s0f1
    - enp225s0f1
  cpu_core_count_config:
    16:
      instance_cpu_core_start_list:
        - 17
        - 1
      threads:
        hpguppi_ibvpkt_thread:
        hpguppi_atasnap_ibv_voltage_thread:
        hpguppi_atasnap_pkt_to_FTP_transpose:
          8
        hpguppi_atasnap_rawdisk_thread:
